#!/usr/bin/env Rscript

###################################################################
####calculate PRS accuracy metrics for disease traits          ####
####Ying Wang (yiwang@broadinstitute.org) in June-2021         ####
###################################################################

########load packages needed########
library(data.table)
library(boot) #for calculating CIs for R2
library(optparse) #for parsing arguments

#########parsing argument options########
option_list <- list(
  make_option(c("--pop"), type = "character", default = NULL, help = "Target ancestry"),
  make_option(c("--pheno"), type = "character", default = NULL, help = "Phenotype name in the phenotype file"),
  make_option(c("--covs"), type = "character", default = NULL, help = "Covariates included in the prediction model, separated by comma"),
  make_option(c("--pc_numbers"), type = "character", default = "PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10", help = "PCs included in the prediction model, separated by comma"),
  make_option(c("--phenofile"), type = "character", default = NULL, help = "Full path and file name to phenotype files (including FID, IID, phenotypes etc.)"),
  make_option(c("--popfile"), type = "character", default = NULL, help = "Full path and file name to the file listing IDs for unrelated individuals in the target population (in the format of FID, IID as the first two columns)"),
  make_option(c("--prsfile"), type = "character", default = NULL, help = "Full path and file name to a *.profile generated by Plink1.* or *.sscore by Plink2.*, note using --sum to get the SCORESUM for Plink 1.* or cols=+scoresums to get SCORE1_SUM for Plink 2.* used in this script"),
  make_option(c("--covfile"), type = "character", default = NULL, help = "Full path and file name to the file including covariates (with headers including FID, IID and covariates)"),
  make_option(c("--pcfile"), type = "character", default = NULL, help = "Full path and file name to the file including PCs (e.g., headers including FID, IID, PC1, PC2, PC3...)"),
  make_option(c("--cohort_name"), type = "character", default = NULL, help = "Discovery GWAS, UKBB or BBJ or combined"),
  make_option(c("--ldref"), type = "character", default = NULL, help = "The LD reference panel used (e.g., 1KG or UKB)"),
  make_option(c("--out"), type = "character", default = NULL, help = "Full path and file name for the output file of the prs accuracy metrics")
)

opt = parse_args(OptionParser(option_list=option_list))

prsfile <- opt$prsfile
popfile <- opt$popfile
phenofile <- opt$phenofile
pheno <- opt$pheno
covfile <- opt$covfile
covs <- opt$covs
pcfile <- opt$pcfile
pc_numbers <- opt$pc_numbers
pop <- opt$pop
cohort <- opt$cohort_name
ldref <- opt$ldref
out <- opt$out

#################reading input files#################
if(prsfile != "NULL"){
  prs_all <- fread(prsfile)
  fn <- tail(strsplit(prsfile, "/")[[1]], 1)
  prefix <- gsub(paste(c(".profile", ".sscore"), collapse = "|"), "",  fn) 
} else{
  print("Error: No PRS score files for input!")
}

if(popfile != "NULL"){
  ids <- fread(popfile, header = F) ##read target population ids
  prs <- prs_all[IID %in% ids$V2,]
} else{
  prs <- prs_all
}

if(phenofile != "NULL"){
  phen <- fread(phenofile) ##including fields FID, IID, ...phenotypes...
  prs[,PHENO := phen[prs, on = "IID"][,get(..pheno)]]
} else{
  print("No phenotype files for input")
}

if(covfile != "NULL" & covs != "NULL"){
  covf <- fread(covfile)
  if(grepl(",", covs)){
    mycovs <- gsub("\\s+","",covs)
    mycovs <- strsplit(mycovs, ",")[[1]]
  } else{
    mycovs <- covs
  }
  prs <- cbind(prs, covf[prs, on = "IID",][, mycovs, with = FALSE])
} else{
  print("No covariates files for input")
}

if(pcfile != "NULL" & pc_numbers != "NULL"){
  pcvecs <- strsplit(pc_numbers, ",")[[1]]
  pcs <- fread(pcfile, select = c("FID", "IID", pcvecs))
  prs <- cbind(prs, pcs[prs, on = "IID",][, ..pcvecs])
} else{
  print("No PC files for input")
}

prs <- na.omit(prs)
N <-  nrow(prs)

##get SCORESUM based on plink version
scores <- c("SCORESUM", "SCORE1_SUM")
prs[,SCORESUM := get(grep(paste(scores, collapse = "|"), names(prs), value = T))]

rsq <- function(formula, data, indices) {
  d <- data[indices,] # allows boot to select sample 
  fit <- lm(formula, data = d)
  return(c(summary(fit)$adj.r.squared, summary(fit)$coefficients[8]))
}

results <- boot(data = prs, statistic = rsq, R = 1000, formula = PHENO ~SCORESUM)

r2 <- results$t0[1]
r2_pval <-  results$t0[2]
r2_se <- sd(results$t[,1])
r2_2.5 <- quantile(results$t[,1],c(0.025,0.975))[[1]]
r2_97.5 <- quantile(results$t[,1],c(0.025,0.975))[[2]]

res <- data.frame(cohort, ldref, pop, prefix, pheno, r2, r2_se, r2_pval, r2_2.5, r2_97.5)

fwrite(res, file = out, sep = "\t")



